server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
#    database: mysql
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
  datasource:
    graduation-system:
      url: ${GRAD_SYSTEM_URL:jdbc:postgresql://localhost:5432/graduation-system-db}
      username: ${GRAD_SYSTEM_USERNAME:graduation-system-admin}
      password: ${GRAD_SYSTEM_PASSWORD:graduation-system-admin}
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect